<a href="https://colab.research.google.com/github/akshitha6162-ui/ML_LAB_2026-27/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas Python Library**

**Introduction to Pandas**

Pandas is an open-source software library written for the Python programming language, primarily used for data manipulation and analysis. It provides powerful and flexible data structures designed to make working with tabular and time-series data both easy and intuitive.

Key features and functionalities of Pandas include: Data Structures:

**Pandas introduces two primary data structures**:

**Series**: A one-dimensional labeled array capable of holding any data type. It can be thought of as a single column in a spreadsheet.

**DataFrame**: A two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table, providing a powerful way to represent and manipulate tabular data.

**What is pandas used for**?

pandas is used throughout the data analysis workflow. With pandas, you can:

Import datasets from databases, spreadsheets, comma-separated values (CSV) files, and more.
Clean datasets, for example, by dealing with missing values.
Tidy datasets by reshaping their structure into a suitable format for analysis.
Aggregate data by calculating summary statistics such as the mean of columns, correlation between them, and more.
Visualize datasets and uncover insights.

**Importing data in pandas**

In [1]:
import pandas as pd

**Importing CSV files**

Use **read_csv()** with the path to the CSV file to read a comma-separated values file

In [2]:
df=pd.read_csv("/content/sample_data/mnist_test.csv")

In [3]:
df.head()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.tail()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df=pd.read_excel("/content/Student_Details(1).xlsx")

In [6]:
df.head()

           Name  Roll No Branch Section Grade
0  Aarav Sharma      101    CSE       A     A
1    Diya Patel      102    ECE       A    B+
2   Rohan Kumar      103     ME       B    A-
3   Sneha Reddy      104    EEE       A     B
4  Vikram Singh      105  CIVIL       C    A+

In [7]:
df=pd.read_json("/content/Student_Details.json")

In [8]:
df.head()

,title,subtitle,students
0,Student Details Report,Academic Records (Sample Data),"{'name': 'Aarav Sharma', 'rollNo': 101, 'branc..."
1,Student Details Report,Academic Records (Sample Data),"{'name': 'Diya Patel', 'rollNo': 102, 'branch'..."
2,Student Details Report,Academic Records (Sample Data),"{'name': 'Rohan Kumar', 'rollNo': 103, 'branch..."
3,Student Details Report,Academic Records (Sample Data),"{'name': 'Sneha Reddy', 'rollNo': 104, 'branch..."
4,Student Details Report,Academic Records (Sample Data),"{'name': 'Vikram Singh', 'rollNo': 105, 'branc..."